---
- name: Prepare
  hosts: all
  tasks:
    - name: install test depedencies
      apt: name={{ packages }} state=present
      vars:
        packages:
          - mysql-server
          - python-pip

    - name: start mysql
      service: name=mysql state=started

    - name: install ansible dependencies
      pip: name=PyMySQL state=present

    - name: set root password for remote login to mysql
      mysql_user: name=root password=fakemasterpassword
